# Generated by Django 3.1.2 on 2020-10-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayomi_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_ayomi',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
